image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

stages:
  - .pre
  - build
  - deploy
  - .post

dockerLogin:
  only:
    - develop
  script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  stage: .pre

buildContiner:
  only:
    - develop
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
  stage: build
  tags: 
    - docker

pushContiner:
  only:
    - develop
  script:
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  stage: deploy
  tags: 
    - docker

dockerLogout:
  only:
    - develop
  script:
    - docker logout ${CI_REGISTRY}
  stage: .post
