image: docker:stable

services:
  - docker:dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest

before_script:
  - docker info
  - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}

build:
  only:
    - develop
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
  tags: 
    - docker

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
